using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using System.IO;
using System.Drawing;
using System.Drawing.Imaging;

namespace DataAccess.Metodos
{
    public class CsHerramientas
    {
        public static int gridvg(DataGridView dgv)
        {
            int valorsito;
            int i;
            i = dgv.SelectedCells[0].RowIndex;
            valorsito = Convert.ToInt32(dgv.Rows[i].Cells[0].Value);

            return valorsito;

        }

        public static string gridvgNom(DataGridView dgv)
        {
            string valorsito;
            int i;
            i = dgv.SelectedCells[0].RowIndex;
            valorsito = dgv.Rows[i].Cells[2].Value.ToString() + " " + dgv.Rows[i].Cells[3].Value.ToString() + " " + dgv.Rows[i].Cells[4].Value.ToString();

            return valorsito;

        }

        public static string ImageToBase64(Image image)
        {
            using (MemoryStream ms = new MemoryStream())
            {
                // Convert Image to byte[]
                image.Save(ms, ImageFormat.Jpeg);
                byte[] imageBytes = ms.ToArray();

                // Convert byte[] to Base64 String
                string base64String = Convert.ToBase64String(imageBytes);
                return base64String;
            }
        }

        public static Image Base64ToImage(string base64String)
        {
            // Convert Base64 String to byte[]
            byte[] imageBytes = Convert.FromBase64String(base64String);
            MemoryStream ms = new MemoryStream(imageBytes, 0,
              imageBytes.Length);

            // Convert byte[] to Image
            ms.Write(imageBytes, 0, imageBytes.Length);
            Image image = Image.FromStream(ms);
            return image;
        }

        public static List<string> getColonias()
          {
               var listColonias = new List<string>();
                   
  listColonias.Add("22 de Septiembre");
listColonias.Add("4a Zona Militar");
listColonias.Add("4 de Marzo");
listColonias.Add("4 Olivos");
listColonias.Add("5 de Mayo");
listColonias.Add("5 de Mayo Sector A");
listColonias.Add("Adolfo de La Huerta");
listColonias.Add("Adolfo Lopez Mateos");
listColonias.Add("Adolfo López Mateos");
listColonias.Add("Agaves Residencial");
listColonias.Add("Agualurca");
listColonias.Add("Akiwiki");
listColonias.Add("Alameda");
listColonias.Add("Alborada");
listColonias.Add("Alcalá Residencial");
listColonias.Add("Alta California Residencial");
listColonias.Add("Altamira");
listColonias.Add("Altares");
listColonias.Add("Altares II");
listColonias.Add("Altares Rancho Grande");
listColonias.Add("Alta Riviera Residencial");
listColonias.Add("Altos de Agustín Residencial");
listColonias.Add("Altos de Aragón");
listColonias.Add("Alto Valle");
listColonias.Add("Alto Valle Sector A");
listColonias.Add("Álvaro Obregón");
listColonias.Add("Amapolas");
listColonias.Add("Ampliación Ladrilleras");
listColonias.Add("Andalucía");
listColonias.Add("Antara Residencial");
listColonias.Add("Antonio Parada Cano");
listColonias.Add("Apolo");
listColonias.Add("Arándanos");
listColonias.Add("Aranjuez Residencial");
listColonias.Add("Arboledas");
listColonias.Add("Arcadia");
listColonias.Add("Arcángel Residencial");
listColonias.Add("Arco Iris");
listColonias.Add("Arizona");
listColonias.Add("Asturias Residencial");
listColonias.Add("Atardeceres");
listColonias.Add("Azores Residencial");
listColonias.Add("Bachoco");
listColonias.Add("Balderrama");
listColonias.Add("Banus");
listColonias.Add("Bella Vista");
listColonias.Add("Bella Vista");
listColonias.Add("Benei Residencial");
listColonias.Add("Benito Juárez");
listColonias.Add("Bernardo Esqueda");
listColonias.Add("Bicentenario Residencial");
listColonias.Add("Buena Ventura");
listColonias.Add("Buena Vista");
listColonias.Add("Buenos Aires");
listColonias.Add("Bugambilias");
listColonias.Add("Burgos Pitic");
listColonias.Add("Burócrata Municipal");
listColonias.Add("Camino Real");
listColonias.Add("Camino Real Del Norte");
listColonias.Add("Campanario");
listColonias.Add("Campestre");
listColonias.Add("Campo Grande Residencial");
listColonias.Add("Cañada de los Negros");
listColonias.Add("Caperuso");
listColonias.Add("Capistrano");
listColonias.Add("Carmen Serdán");
listColonias.Add("Casa Blanca");
listColonias.Add("Casa Bonita");
listColonias.Add("Casa Bonita II");
listColonias.Add("Casa Grande Residencial I");
listColonias.Add("Casa Grande Residencial II");
listColonias.Add("Casa Grande Residencial III");
listColonias.Add("Casa Linda");
listColonias.Add("Casa Real");
listColonias.Add("Castello Residencial");
listColonias.Add("Catalinas Residencial");
listColonias.Add("Cataviñas Residencial");
listColonias.Add("Centenario");
listColonias.Add("Central de Abastos");
listColonias.Add("Centro Norte");
listColonias.Add("Centro Oriente");
listColonias.Add("Centro SCT Sonora");
listColonias.Add("Cerrada Coronado");
listColonias.Add("Cerrada Cucurpe");
listColonias.Add("Cerrada de La Capilla");
listColonias.Add("Cerrada de Minas");
listColonias.Add("Cerrada Diamante");
listColonias.Add("Cerrada Norwalk");
listColonias.Add("Cerrada Pimas");
listColonias.Add("Cerro Apache");
listColonias.Add("Cerro Colorado");
listColonias.Add("Cerro de La Campana");
listColonias.Add("Cerro de La Cruz");
listColonias.Add("Chino Abelardo");
listColonias.Add("Choyal");
listColonias.Add("Chula Vista");
listColonias.Add("CNOP");
listColonias.Add("Colina Blanca");
listColonias.Add("Colinas");
listColonias.Add("Colinas Del Bachoco");
listColonias.Add("Colinas del Sur");
listColonias.Add("Colinas de San Javier");
listColonias.Add("Colinas II");
listColonias.Add("Coloso");
listColonias.Add("Coloso Bajo");
listColonias.Add("Coloso Norte");
listColonias.Add("Coloso Oriente");
listColonias.Add("Comercial Cedros");
listColonias.Add("Compostela Residencial");
listColonias.Add("Condesa");
listColonias.Add("Condominio Hacienda Real");
listColonias.Add("Condominios San Pablo");
listColonias.Add("Conquistadores");
listColonias.Add("Constitución");
listColonias.Add("Corceles Residencial");
listColonias.Add("Córdoba Residencial");
listColonias.Add("Coronado");
listColonias.Add("Cortijo Periodista");
listColonias.Add("Cortijo Pioneros");
listColonias.Add("Costa del Sol");
listColonias.Add("Costa del Sol II");
listColonias.Add("Country Club");
listColonias.Add("Country Club Residencial");
listColonias.Add("Cruz Gálvez");
listColonias.Add("Cuartel Pitic");
listColonias.Add("Cuartel XX Café Combate");
listColonias.Add("Cuartel Zona");
listColonias.Add("Cuauhtémoc");
listColonias.Add("Cucurpe II");
listColonias.Add("Cumbres Residencial");
listColonias.Add("Cumbres Residencial III");
listColonias.Add("Del Bosque");
listColonias.Add("Del Razo");
listColonias.Add("División del Norte");
listColonias.Add("Dunas");
listColonias.Add("Dunas III");
listColonias.Add("El Apache");
listColonias.Add("El Buey");
listColonias.Add("El Conquistador");
listColonias.Add("El Cortijo");
listColonias.Add("El Cortijo UNISON");
listColonias.Add("El Dorado");
listColonias.Add("El Encanto");
listColonias.Add("El Encanto Residencial");
listColonias.Add("El Esplendor");
listColonias.Add("El Jito");
listColonias.Add("El Llanito");
listColonias.Add("El Llano");
listColonias.Add("El Malecón");
listColonias.Add("El Mariachi");
listColonias.Add("El Mezquite");
listColonias.Add("El Progreso");
listColonias.Add("El Ranchito");
listColonias.Add("El Recodo");
listColonias.Add("Emiliano Zapata");
listColonias.Add("Equip Educativo");
listColonias.Add("Eusebio Kino");
listColonias.Add("Ferrocarrilera");
listColonias.Add("Flamingos");
listColonias.Add("Floresta");
listColonias.Add("Floresta Villa Almendras");
listColonias.Add("Floresta Villa Cipreces");
listColonias.Add("Floresta Villa Ciruelos");
listColonias.Add("Floresta Villa Fresnos");
listColonias.Add("Florida");
listColonias.Add("FONHAPO");
listColonias.Add("Fovissste");
listColonias.Add("Francisco E. Kino ISSSTESON");
listColonias.Add("Francisco Romero");
listColonias.Add("Francisco Villa");
listColonias.Add("Fuente de Piedra");
listColonias.Add("Fuentes Del Centenario");
listColonias.Add("Fuentes Del Mezquital");
listColonias.Add("Gala");
listColonias.Add("Gala II");
listColonias.Add("Genova Residencial");
listColonias.Add("Girasoles");
listColonias.Add("Guajiros");
listColonias.Add("Hacienda de La Flor");
listColonias.Add("Hacienda Del Pedregal");
listColonias.Add("Hacienda Del Sol");
listColonias.Add("Hacienda los Alcatraces");
listColonias.Add("Hacienda los Lirios");
listColonias.Add("Hacienda Residencial");
listColonias.Add("Hacienda Residencial Condominal");
listColonias.Add("Haciendas del Sur");
listColonias.Add("H Ayuntamiento");
listColonias.Add("Heberto Castillo");
listColonias.Add("Hermosa Provincia");
listColonias.Add("Hermosillo Centro");
listColonias.Add("Hermosillo (Gral. Ignacio Pesqueira García)");
listColonias.Add("Inalámbrica");
listColonias.Add("Insurgentes");
listColonias.Add("Internacional");
listColonias.Add("Invasión Altares");
listColonias.Add("Invasión Antorcha Campesina");
listColonias.Add("Invasión El Chaparral");
listColonias.Add("Invasión El Mirador");
listColonias.Add("Issste Federal");
listColonias.Add("Isssteson");
listColonias.Add("Isssteson Centenario");
listColonias.Add("ISSSTESON Colegio Lux");
listColonias.Add("Isssteson Norte");
listColonias.Add("Jacarandas");
listColonias.Add("Jacinto Lopez");
listColonias.Add("Jardines");
listColonias.Add("Jardines de Hermosillo");
listColonias.Add("Jardines de Mónaco");
listColonias.Add("Jerez Del Valle");
listColonias.Add("Jesús Garcia");
listColonias.Add("Jesús Vega Aguilar");
listColonias.Add("Jorge Valdez Muñoz");
listColonias.Add("Joyas del Bachoco");
listColonias.Add("Kikapu");
listColonias.Add("Kukapa");
listColonias.Add("La Antorcha Campesina");
listColonias.Add("La Campana");
listColonias.Add("La Campiña");
listColonias.Add("La Campiña II, III, IV, V");
listColonias.Add("La Caridad");
listColonias.Add("La Cholla");
listColonias.Add("La Cholla II Sección");
listColonias.Add("La Encantada");
listColonias.Add("La Huerta");
listColonias.Add("La Joya");
listColonias.Add("La Joya Villa de Las Esmeraldas");
listColonias.Add("La Joya Villa de los Diamantes");
listColonias.Add("La Joya Villa de los Zafiros");
listColonias.Add("La Lengueta");
listColonias.Add("La Manga");
listColonias.Add("La Manga");
listColonias.Add("La Matanza");
listColonias.Add("La Misión");
listColonias.Add("La Mosca");
listColonias.Add("La Paloma Residencial I");
listColonias.Add("La Paloma Residencial II");
listColonias.Add("La Primavera");
listColonias.Add("La Rioja Residencial");
listColonias.Add("Las Acacias");
listColonias.Add("Las Aves");
listColonias.Add("Las Carretas");
listColonias.Add("Las Diligencias");
listColonias.Add("Las Dunas II");
listColonias.Add("Las Flores");
listColonias.Add("Las Granjas");
listColonias.Add("Las Isabeles");
listColonias.Add("Las Lomas");
listColonias.Add("Las Lomas de Cortes");
listColonias.Add("Las Lomas del Pitic");
listColonias.Add("Las Lomas Del Sol");
listColonias.Add("Las Lomas Del Sur");
listColonias.Add("Las Lomas Privada Del Bosque");
listColonias.Add("Las Lomas Privada las Lomas");
listColonias.Add("Las Lomas Real Del Parque");
listColonias.Add("Las Lomas Sección Bonita");
listColonias.Add("Las Lomas Sección Bonita 2");
listColonias.Add("Las Lomas Sección Castaños");
listColonias.Add("Las Lomas Sección El Paraíso");
listColonias.Add("Las Lomas Sección los Manzanos");
listColonias.Add("Las Lomas Sección Sec");
listColonias.Add("Las Minitas");
listColonias.Add("Las Palmas");
listColonias.Add("Las Palmas");
listColonias.Add("Las Pilas");
listColonias.Add("Las Plazas");
listColonias.Add("Las Praderas");
listColonias.Add("Las Praderas IV");
listColonias.Add("Las Praderas Norte");
listColonias.Add("Las Praderas Sur");
listColonias.Add("Las Provincias");
listColonias.Add("Las Quintas");
listColonias.Add("Las Quintas Secc Dorada");
listColonias.Add("Las Riberas del Pitic");
listColonias.Add("Las Torres");
listColonias.Add("Las Villas");
listColonias.Add("Laura Alicia Frías de Lopez Nogales");
listColonias.Add("La Ventana");
listColonias.Add("La Verbena");
listColonias.Add("Ley 57");
listColonias.Add("Libertad");
listColonias.Add("Llano Verde");
listColonias.Add("Loma Blanca");
listColonias.Add("Loma Linda");
listColonias.Add("Lomas Altas");
listColonias.Add("Lomas Altas Periferia");
listColonias.Add("Lomas de Lindavista");
listColonias.Add("Lomas Del Mirador");
listColonias.Add("Lomas del Norte");
listColonias.Add("Lomas del Pitic");
listColonias.Add("Lomas de Madrid");
listColonias.Add("Lomas de Reforma");
listColonias.Add("López Portillo");
listColonias.Add("Loreto");
listColonias.Add("Los Álamos");
listColonias.Add("Los Álamos");
listColonias.Add("Los Altos Residencial");
listColonias.Add("Los Angeles");
listColonias.Add("Los Arcos");
listColonias.Add("Los Arroyos");
listColonias.Add("Los Arroyos Sección Los Manantiales");
listColonias.Add("Los Canarios");
listColonias.Add("Los Girasoles");
listColonias.Add("Los Igualados");
listColonias.Add("Los Lagos");
listColonias.Add("Los Lingotes");
listColonias.Add("Los Manantiales");
listColonias.Add("Los Mirasoles");
listColonias.Add("Los Naranjos");
listColonias.Add("Los Olivos");
listColonias.Add("Los Pinos");
listColonias.Add("Los Pinos Residencial");
listColonias.Add("Los Poetas");
listColonias.Add("Los Portales");
listColonias.Add("Los Rosales");
listColonias.Add("Los Sabinos");
listColonias.Add("Los Santos Residencial");
listColonias.Add("Los Sauces");
listColonias.Add("Los Tulipanes");
listColonias.Add("Los Viñedos I");
listColonias.Add("Los Viñedos II");
listColonias.Add("Luis Donaldo Colosio");
listColonias.Add("Luis Encinas");
listColonias.Add("Machi Lopez");
listColonias.Add("Magisterial");
listColonias.Add("Mallorca Residencial");
listColonias.Add("Manuel Gómez Morin");
listColonias.Add("Margaritas Olivos");
listColonias.Add("Marsella Residencial");
listColonias.Add("Mártires de Cananea");
listColonias.Add("Mediterráneo Residencial");
listColonias.Add("Metalera");
listColonias.Add("Mezquital Del Oro");
listColonias.Add("Miguel Ángel Jiménez");
listColonias.Add("Miguel Hidalgo");
listColonias.Add("Miguel Valencia");
listColonias.Add("Miguel Valencia");
listColonias.Add("Milán");
listColonias.Add("Militar");
listColonias.Add("Mini Parque Industrial");
listColonias.Add("Misión Del Arco");
listColonias.Add("Misión Del Real");
listColonias.Add("Misión Del Sol");
listColonias.Add("Misioneros");
listColonias.Add("Misión los Lirios");
listColonias.Add("Misión San Cristóbal");
listColonias.Add("Misión San Ignacio");
listColonias.Add("Misión San Jerónimo");
listColonias.Add("Modelo");
listColonias.Add("Modelo Centro (Guaymas J. Sierra)");
listColonias.Add("Modelo Norte");
listColonias.Add("Modelo Sur Retornos");
listColonias.Add("Mónaco Privada Residencial");
listColonias.Add("Montebello");
listColonias.Add("Montecarlo");
listColonias.Add("Monterosa Residencial");
listColonias.Add("Morelos");
listColonias.Add("Murano Residencial");
listColonias.Add("Nacameri");
listColonias.Add("Nazareo Residencial");
listColonias.Add("Norberto Ortega");
listColonias.Add("Nueva Castilla");
listColonias.Add("Nueva Creación");
listColonias.Add("Nueva España");
listColonias.Add("Nueva Esperanza");
listColonias.Add("Nueva Estación");
listColonias.Add("Nueva Galicia");
listColonias.Add("Nueva Palmira");
listColonias.Add("Nueva Victoria");
listColonias.Add("Nuevo Hermosillo");
listColonias.Add("Nuevo Horizonte");
listColonias.Add("Nuevo Horizonte");
listColonias.Add("Nuevo Sahuaro");
listColonias.Add("Oasis del Sol");
listColonias.Add("Oasis Lantana");
listColonias.Add("Oasis Palmira");
listColonias.Add("Oasis Santa Fe");
listColonias.Add("Oasis Solana");
listColonias.Add("Obispo Residencial");
listColonias.Add("Obispos Residencial II");
listColonias.Add("Oficina Federal de Hacienda");
listColonias.Add("Oficinas Federales");
listColonias.Add("Olivares");
listColonias.Add("Olivares Norte");
listColonias.Add("Olivos");
listColonias.Add("Opatas");
listColonias.Add("Palacio de Gobierno Del Estado de Sonora");
listColonias.Add("Palermo Sección Bárbara");
listColonias.Add("Palermo Sección Ferrara");
listColonias.Add("Palermo Sección Partanna");
listColonias.Add("Palermo Sección Veneto");
listColonias.Add("Palma Dorada");
listColonias.Add("Palmar Del Sol");
listColonias.Add("Palo Fierro");
listColonias.Add("Palo Verde");
listColonias.Add("Paloverde Indeur Los Olivos");
listColonias.Add("Palo Verde Norte");
listColonias.Add("Palo Verde Sur");
listColonias.Add("Papagos");
listColonias.Add("Parque Industrial");
listColonias.Add("Parque Industrial");
listColonias.Add("Parque Industrial Dynatech");
listColonias.Add("Parque Industrial Dynatech Sur");
listColonias.Add("Parque Industrial Hermosillo Norte");
listColonias.Add("Parque Industrial La Labor");
listColonias.Add("Parque Industrial Pimex");
listColonias.Add("Parque Industrial Sonora");
listColonias.Add("Parque Madero Norte");
listColonias.Add("Parque Versalles");
listColonias.Add("Paseo de La Colina I");
listColonias.Add("Paseo de La Colina II");
listColonias.Add("Paseo de las Margaritas");
listColonias.Add("Paseo de las Misiones");
listColonias.Add("Paseo de las Palmas");
listColonias.Add("Paseo Del Palmar");
listColonias.Add("Paseo Del Sahuaro");
listColonias.Add("Paseo del Sol");
listColonias.Add("Paseo Real Residencial");
listColonias.Add("Paseo San Angel");
listColonias.Add("Paseo San Ángel Sección Las Placitas");
listColonias.Add("Paseo San Ángel Sección Las Placitas I,II,III, IV");
listColonias.Add("Paseo San Ángel Sección Los Álamos");
listColonias.Add("Paseos del Pedregal");
listColonias.Add("PEMEX");
listColonias.Add("Periodista");
listColonias.Add("Periodista Sector A");
listColonias.Add("Perisur");
listColonias.Add("Piedra Bola (Pedregal de la Villa)");
listColonias.Add("Pilares");
listColonias.Add("Pimentel");
listColonias.Add("Pitic");
listColonias.Add("Pitic Norte");
listColonias.Add("Pitic Oriente");
listColonias.Add("Pitic Sector B");
listColonias.Add("Pitic Sector C");
listColonias.Add("Pitic Sector D");
listColonias.Add("Plaza de Las Franquicias");
listColonias.Add("Plaza Grande");
listColonias.Add("Plaza Inn");
listColonias.Add("Plaza Real");
listColonias.Add("Popular");
listColonias.Add("Portal del Lago");
listColonias.Add("Portal Del Pitic");
listColonias.Add("Portal de Romanza");
listColonias.Add("Portón Del Arco");
listColonias.Add("Praderas Del Real");
listColonias.Add("Praderas Del Sol");
listColonias.Add("Praderas Del Valle");
listColonias.Add("Prados de Bugambilias");
listColonias.Add("Prados de Bugambilias II");
listColonias.Add("Prados Del Centenario");
listColonias.Add("Prados Del Sol");
listColonias.Add("Primero Hermosillo");
listColonias.Add("Privada Azulejos");
listColonias.Add("Privada Casa Blanca");
listColonias.Add("Privada Caturegli");
listColonias.Add("Privada Córdoba");
listColonias.Add("Privada de los Azulejos");
listColonias.Add("Privada Leyendas");
listColonias.Add("Privada Mixcoac");
listColonias.Add("Privada Quinta Emilia");
listColonias.Add("Privada Residencial del Pedregal");
listColonias.Add("Privada Robles");
listColonias.Add("Privada Rosales");
listColonias.Add("Privada San Germán");
listColonias.Add("Privadas Del Bosque");
listColonias.Add("Privadas del Mirador");
listColonias.Add("Privadas del Real");
listColonias.Add("Privadas del Real III Sección");
listColonias.Add("Privadas del Real II Sección");
listColonias.Add("Privadas del Real IV Sección");
listColonias.Add("Privadas del Sauce");
listColonias.Add("Privadas Residenciales");
listColonias.Add("Privada Universidad");
listColonias.Add("Privada Victoria");
listColonias.Add("Progresista");
listColonias.Add("Proyecto Rio Sonora");
listColonias.Add("Pueblitos");
listColonias.Add("Pueblo Alegre");
listColonias.Add("Pueblo Alto");
listColonias.Add("Pueblo Bonito");
listColonias.Add("Pueblo del Ángel");
listColonias.Add("Pueblo Del Sol");
listColonias.Add("Pueblo de Oro");
listColonias.Add("Pueblo Escondido");
listColonias.Add("Pueblo Nuevo");
listColonias.Add("Puerta de Hierro");
listColonias.Add("Puerta del Rey");
listColonias.Add("Puerta del Sol");
listColonias.Add("Puerta Esmeralda");
listColonias.Add("Puerta Grande");
listColonias.Add("Puerta Real 8a Etapa");
listColonias.Add("Puerta Real Residencial");
listColonias.Add("Puerta Real Residencial III");
listColonias.Add("Puerta Real Residencial IV");
listColonias.Add("Puerta Real Residencial VI");
listColonias.Add("Puerta Real Residencial VII");
listColonias.Add("Puesta del Sol");
listColonias.Add("Punta de Lago");
listColonias.Add("Quinta Emilia");
listColonias.Add("Quinta La Paloma");
listColonias.Add("Quinta Real");
listColonias.Add("Quintas del Sol Residencial");
listColonias.Add("Quintas Galicia");
listColonias.Add("Racquet Club II Sección Norte");
listColonias.Add("Racquet Club I Sección Sur");
listColonias.Add("Rancho Bonito");
listColonias.Add("Real Del Arco");
listColonias.Add("Real Del Cardo");
listColonias.Add("Real Del Carmen");
listColonias.Add("Real del Carmen II");
listColonias.Add("Real del Carmen III");
listColonias.Add("Real del Carmen IV");
listColonias.Add("Real del Carmen V");
listColonias.Add("Real del Catorce");
listColonias.Add("Real Del Cobre");
listColonias.Add("Real Del Llano");
listColonias.Add("Real del Valle");
listColonias.Add("Real de Minas");
listColonias.Add("Real de Montejo");
listColonias.Add("Real de Quiroga");
listColonias.Add("Red 2000");
listColonias.Add("Reforma Norte");
listColonias.Add("Renacimiento");
listColonias.Add("Residencial Bretaña");
listColonias.Add("Residencial de Anza");
listColonias.Add("Residencial Kino");
listColonias.Add("Residencial La Cima");
listColonias.Add("Residencial Navarrete");
listColonias.Add("Residencial Peñasco");
listColonias.Add("Residencial Pima");
listColonias.Add("Residencial Villa Tozzaly");
listColonias.Add("Retorno de La Misión");
listColonias.Add("Retorno Maderas");
listColonias.Add("Revolución I");
listColonias.Add("Revolución II");
listColonias.Add("Rinconada de La Cruz");
listColonias.Add("Rinconada de Nuevo Leon");
listColonias.Add("Rincón Agradable");
listColonias.Add("Rincón de La Herradura");
listColonias.Add("Rincón Del Marquez");
listColonias.Add("Rincón de Palmas");
listColonias.Add("Río de Plata");
listColonias.Add("Rio Grande");
listColonias.Add("Rivello Residencial");
listColonias.Add("Romanza Residencial");
listColonias.Add("Rosario I de Piedra");
listColonias.Add("Sacramento Residencial");
listColonias.Add("Sahuaro");
listColonias.Add("Sahuaro Final");
listColonias.Add("Sahuaro Indeco");
listColonias.Add("Salvatierra Residencial");
listColonias.Add("San Andrés Residencial");
listColonias.Add("San Angel");
listColonias.Add("San Antonio");
listColonias.Add("San Benito");
listColonias.Add("San Bernardino");
listColonias.Add("San Bosco");
listColonias.Add("San Diego");
listColonias.Add("San Francisco");
listColonias.Add("San Isidro");
listColonias.Add("San Javier");
listColonias.Add("San Jose de las Minitas");
listColonias.Add("San Juan");
listColonias.Add("San Lorenzo");
listColonias.Add("San Luis");
listColonias.Add("San Luis Norte");
listColonias.Add("San Luis Rey");
listColonias.Add("San Marcos");
listColonias.Add("San Pablo");
listColonias.Add("San Sebastián");
listColonias.Add("Santa Bárbara");
listColonias.Add("Santa Cecilia");
listColonias.Add("Santa Engracia");
listColonias.Add("Santa Fe");
listColonias.Add("Santa Isabel");
listColonias.Add("Santa Lucia");
listColonias.Add("Santa Maria");
listColonias.Add("Sector Industrial Presa");
listColonias.Add("Seminario");
listColonias.Add("Seminario Mayor");
listColonias.Add("Senda Dorada");
listColonias.Add("Sierra Alta");
listColonias.Add("Sierra Blanca");
listColonias.Add("Sierra Bonita");
listColonias.Add("Sierra Clara");
listColonias.Add("Sierra Vista");
listColonias.Add("Sol Aguilar");
listColonias.Add("Soleil Residencial");
listColonias.Add("Solidaridad");
listColonias.Add("Solidaridad II");
listColonias.Add("Solidaridad III");
listColonias.Add("Solidaridad IV");
listColonias.Add("Solidaridad V");
listColonias.Add("Solidaridad Vildosola");
listColonias.Add("Sonacer");
listColonias.Add("Sonomex");
listColonias.Add("Stanza Solare Residencial");
listColonias.Add("Staus");
listColonias.Add("Terranova");
listColonias.Add("Terrazas Del Mirador");
listColonias.Add("Tierra Blanca");
listColonias.Add("Tierra Colorada");
listColonias.Add("Tierra Nueva");
listColonias.Add("Tiro Al Blanco");
listColonias.Add("Tirocapes");
listColonias.Add("Topacio Residencial");
listColonias.Add("Torcaz Residencial");
listColonias.Add("Torreón");
listColonias.Add("Torreplata");
listColonias.Add("Tubac");
listColonias.Add("Tumacacori");
listColonias.Add("Unión de Colonos");
listColonias.Add("Unión de Ladrilleros");
listColonias.Add("Universidad");
listColonias.Add("Urbi Alameda Encinos I,II,III");
listColonias.Add("Urbi Alameda Los Fresnos");
listColonias.Add("Urbi Villa Campestre");
listColonias.Add("Urbi Villa del Cedro");
listColonias.Add("Urbi Villa del Rey");
listColonias.Add("Urbi Villa del Rey II");
listColonias.Add("Urbi Villa del Rey III");
listColonias.Add("Urbi Villa del Rey IV");
listColonias.Add("Valle Bonito");
listColonias.Add("Valle de Arandas");
listColonias.Add("Valle del Lago");
listColonias.Add("Valle del Marquez");
listColonias.Add("Valle de los Almendros");
listColonias.Add("Valle Del Portal");
listColonias.Add("Valle del Quiroga");
listColonias.Add("Valle Del Sol");
listColonias.Add("Valle Dorado");
listColonias.Add("Valle Escondido");
listColonias.Add("Valle Grande");
listColonias.Add("Valle Hermoso");
listColonias.Add("Valle Santa Mónica");
listColonias.Add("Valle Verde");
listColonias.Add("Villa Bonita");
listColonias.Add("Villa California");
listColonias.Add("Villa Colonial");
listColonias.Add("Villa Colonial II");
listColonias.Add("Villa de Cassia");
listColonias.Add("Villa de Los Corceles");
listColonias.Add("Villa del Pitic");
listColonias.Add("Villa del Prado");
listColonias.Add("Villa Del Real");
listColonias.Add("Villa Del Rey");
listColonias.Add("Villa del Rey Sección Almendros II");
listColonias.Add("Villa del Rey Sección Almendros III");
listColonias.Add("Villa del Rey Sección Castaños I");
listColonias.Add("Villa del Rey Sección Castaños II");
listColonias.Add("Villa del Rey Sección Castaños III");
listColonias.Add("Villa del Rey Sección Castaños IV");
listColonias.Add("Villa del Rey Sección Los Almendros I");
listColonias.Add("Villa del Rey Sección Manzanos II");
listColonias.Add("Villa de Parras");
listColonias.Add("Villa de Seris Norte");
listColonias.Add("Villa de Seris Sur");
listColonias.Add("Villa Dorada");
listColonias.Add("Villa Florencia");
listColonias.Add("Villa Fontana");
listColonias.Add("Villa Guadalupe");
listColonias.Add("Villa Hermosa");
listColonias.Add("Villa las Lomas");
listColonias.Add("Villa Lourdes");
listColonias.Add("Villa Mercedes");
listColonias.Add("Villa Merlot Residencial");
listColonias.Add("Villa Residencial Bonita Etapa I al XII");
listColonias.Add("Villa Satélite");
listColonias.Add("Villa Sauces");
listColonias.Add("Villas Del Cortes");
listColonias.Add("Villas Del Cortijo");
listColonias.Add("Villas del Mediterráneo Etapa I");
listColonias.Add("Villas del Mediterráneo Etapa II");
listColonias.Add("Villas del Mediterráneo Etapa III");
listColonias.Add("Villas del Mediterráneo Etapa IV");
listColonias.Add("Villas Del Palmar");
listColonias.Add("Villas Del Palmar 2");
listColonias.Add("Villas Del Sur");
listColonias.Add("Villas de Romanza");
listColonias.Add("Villas de Turin");
listColonias.Add("Villa Sol");
listColonias.Add("Villa Sonora");
listColonias.Add("Villas Residencial");
listColonias.Add("Villa Sureña");
listColonias.Add("Villa Toscana");
listColonias.Add("Villa Verde");
listColonias.Add("Villa Verde II");
listColonias.Add("Villa Verde III");
listColonias.Add("Virreyes");
listColonias.Add("Vista Bella");
listColonias.Add("Vista del Lago");
listColonias.Add("Vista del Sol");
listColonias.Add("Vista Real");
listColonias.Add("Y Griega");
listColonias.Add("Zona Militar Cuartel XV");
listColonias.Add("Fuera de hermosillo");

                   
                return listColonias;
           
        
        
          }

        public static List<string> getPaises()
        {

            var listPaises = new List<string>();
            listPaises.Add("Africa del Sur ");
            listPaises.Add("Angola ");
            listPaises.Add("Argelia ");
            listPaises.Add("Benin ");
            listPaises.Add("Botswana ");
            listPaises.Add("Burkina Faso ");
            listPaises.Add("Burundi ");
            listPaises.Add("Camerun ");
            listPaises.Add("Cape Verde ");
            listPaises.Add("Chad ");
            listPaises.Add("Comoros ");
            listPaises.Add("Congo ");
            listPaises.Add("Costa de Marfíl ");
            listPaises.Add("Djibouti ");
            listPaises.Add("Egipto ");
            listPaises.Add("Eritrea ");
            listPaises.Add("Etiopia ");
            listPaises.Add("Gabon ");
            listPaises.Add("Gambia ");
            listPaises.Add("Ghana ");
            listPaises.Add("Guinea ");
            listPaises.Add("Guinea-Bissau ");
            listPaises.Add("Guinea Equatorial ");
            listPaises.Add("Kenia ");
            listPaises.Add("Lesotho ");
            listPaises.Add("Liberia ");
            listPaises.Add("Libia ");
            listPaises.Add("Madagascar ");
            listPaises.Add("Malawi ");
            listPaises.Add("Mali ");
            listPaises.Add("Marruecos ");
            listPaises.Add("Mauricio ");
            listPaises.Add("Mauritania ");
            listPaises.Add("Mozambique ");
            listPaises.Add("Namibia ");
            listPaises.Add("Niger ");
            listPaises.Add("Nigeria ");
            listPaises.Add("Rep.Centroafricana ");
            listPaises.Add("Rep.Dem.Congo ");
            listPaises.Add("Reunion ");
            listPaises.Add("Ruanda ");
            listPaises.Add("Sahara ");
            listPaises.Add("Santa Helena ");
            listPaises.Add("Sao Tome & Principe ");
            listPaises.Add("Senegal ");
            listPaises.Add("Seychelles ");
            listPaises.Add("Sierra Leona ");
            listPaises.Add("Somalia ");
            listPaises.Add("Sudan ");
            listPaises.Add("Sur Africa ");
            listPaises.Add("Swaziland ");
            listPaises.Add("Tanzania ");
            listPaises.Add("Togo ");
            listPaises.Add("Tunisia ");
            listPaises.Add("Uganda ");
            listPaises.Add("Zambia ");
            listPaises.Add("Zimbabwe ");
            listPaises.Add("Belice ");
            listPaises.Add("Costa Rica ");
            listPaises.Add("El Salvador ");
            listPaises.Add("Guatemala ");
            listPaises.Add("Honduras ");
            listPaises.Add("Mexico ");
            listPaises.Add("Nicaragua ");
            listPaises.Add("Panama ");
            listPaises.Add("Canada ");
            listPaises.Add("Estados Unidos ");
            listPaises.Add("Groenlandia ");
            listPaises.Add("Mexico ");
            listPaises.Add("Argentina ");
            listPaises.Add("Bolivia ");
            listPaises.Add("Brasil ");
            listPaises.Add("Chile ");
            listPaises.Add("Colombia ");
            listPaises.Add("Ecuador ");
            listPaises.Add("Guayana Francesa ");
            listPaises.Add("Guyana ");
            listPaises.Add("Islas Malvinas ");
            listPaises.Add("Paraguay ");
            listPaises.Add("Peru ");
            listPaises.Add("Surinam ");
            listPaises.Add("Uruguay ");
            listPaises.Add("Venezuela ");
            listPaises.Add("Afganistan ");
            listPaises.Add("Armenia ");
            listPaises.Add("Azerbaijan ");
            listPaises.Add("Bangladesh ");
            listPaises.Add("Bhutan ");
            listPaises.Add("Brunei Darussulam ");
            listPaises.Add("Camboya ");
            listPaises.Add("Corea del Norte ");
            listPaises.Add("Corea del Sur ");
            listPaises.Add("China ");
            listPaises.Add("Filipinas ");
            listPaises.Add("Georgia ");
            listPaises.Add("Hong Kong ");
            listPaises.Add("India ");
            listPaises.Add("Indonesia ");
            listPaises.Add("Japon ");
            listPaises.Add("Kazakhstan ");
            listPaises.Add("Kyrgyzstan ");
            listPaises.Add("Laos ");
            listPaises.Add("Macao ");
            listPaises.Add("Malasia ");
            listPaises.Add("Maldivas ");
            listPaises.Add("Mongolia ");
            listPaises.Add("Myanmar (Burma) ");
            listPaises.Add("Nepal ");
            listPaises.Add("Pakistan ");
            listPaises.Add("Singapur ");
            listPaises.Add("Sri Lanka (Ceilan) ");
            listPaises.Add("Tailandia ");
            listPaises.Add("Taiwan ");
            listPaises.Add("Tajikistan ");
            listPaises.Add("Timor Oriental ");
            listPaises.Add("Turkmenistan ");
            listPaises.Add("Uzbekistan ");
            listPaises.Add("Vietnam ");
            listPaises.Add("Antillas Holandesas ");
            listPaises.Add("Antigua y Barbuda ");
            listPaises.Add("Aruba ");
            listPaises.Add("Bahamas ");
            listPaises.Add("Barbados ");
            listPaises.Add("Bermudas ");
            listPaises.Add("Cuba ");
            listPaises.Add("Dominica ");
            listPaises.Add("Granada ");
            listPaises.Add("Guadalupe ");
            listPaises.Add("Haiti ");
            listPaises.Add("Islas Caiman ");
            listPaises.Add("Islas Virgenes (GB) ");
            listPaises.Add("Islas Virgenes (US) ");
            listPaises.Add("Jamaica ");
            listPaises.Add("Martinica ");
            listPaises.Add("Puerto Rico ");
            listPaises.Add("Republica Dominicana ");
            listPaises.Add("San Cristobal-Nevis ");
            listPaises.Add("San Vincente y las Granadinas ");
            listPaises.Add("Santa Lucia ");
            listPaises.Add("Trinidad & Tobago ");
            listPaises.Add("Albania ");
            listPaises.Add("Andorra ");
            listPaises.Add("Belarusia ");
            listPaises.Add("Bosnia ");
            listPaises.Add("Bulgaria ");
            listPaises.Add("Croasia ");
            listPaises.Add("Chipre ");
            listPaises.Add("Eslovenia ");
            listPaises.Add("Estonia ");
            listPaises.Add("Guerney ");
            listPaises.Add("Hungria ");
            listPaises.Add("Islandia ");
            listPaises.Add("Islas Faroe ");
            listPaises.Add("Jersey ");
            listPaises.Add("Latvia ");
            listPaises.Add("Liechtenstein ");
            listPaises.Add("Lituania ");
            listPaises.Add("Macedionia ");
            listPaises.Add("Malta ");
            listPaises.Add("Moldova ");
            listPaises.Add("Monaco ");
            listPaises.Add("Noruega ");
            listPaises.Add("Polonia ");
            listPaises.Add("Republica Checa ");
            listPaises.Add("Republica Eslovaca ");
            listPaises.Add("Rumania ");
            listPaises.Add("Rusia ");
            listPaises.Add("San Marino ");
            listPaises.Add("Santa Sede (Vaticano) ");
            listPaises.Add("Suiza ");
            listPaises.Add("Ucrania ");
            listPaises.Add("Union Europea ");
            listPaises.Add("Yugoslavia ");
            listPaises.Add("Alemania ");
            listPaises.Add("Austria ");
            listPaises.Add("Belgica ");
            listPaises.Add("Dinamarca ");
            listPaises.Add("España ");
            listPaises.Add("Finlandia ");
            listPaises.Add("Francia ");
            listPaises.Add("Grecia ");
            listPaises.Add("Holanda ");
            listPaises.Add("Irlanda ");
            listPaises.Add("Italia ");
            listPaises.Add("Luxemburgo ");
            listPaises.Add("Portugal ");
            listPaises.Add("Reino Unido ");
            listPaises.Add("Suecia ");
            listPaises.Add("Arabia Saudita ");
            listPaises.Add("Bahrain ");
            listPaises.Add("Emiratos Arabes Unidos ");
            listPaises.Add("Irak ");
            listPaises.Add("Iran ");
            listPaises.Add("Israel ");
            listPaises.Add("Jordania ");
            listPaises.Add("Kuwait ");
            listPaises.Add("Libano ");
            listPaises.Add("Oman ");
            listPaises.Add("Palestina ");
            listPaises.Add("Qatar ");
            listPaises.Add("Siria ");
            listPaises.Add("Turquia ");
            listPaises.Add("Yemen ");
            listPaises.Add("Australia ");
            listPaises.Add("Fiji ");
            listPaises.Add("Guam ");
            listPaises.Add("Islas Marshall ");
            listPaises.Add("Islas Solomon ");
            listPaises.Add("Kiribati ");
            listPaises.Add("Micronesia ");
            listPaises.Add("Nueva Caledonia ");
            listPaises.Add("Nueva Zealandia ");
            listPaises.Add("Papua Nueva Guinea ");
            listPaises.Add("Polinesia Francesa ");
            listPaises.Add("Samoa ");
            listPaises.Add("Tonga ");
            listPaises.Add("Vanuatu");
               



            return listPaises;
        }

        public static List<string> getMunicipios()
        { 
        
        var listmuni = new  List<string>();
        listmuni.Add("Aconchi");
        listmuni.Add("Agua Prieta");
        listmuni.Add("Álamos");
        listmuni.Add("Altar");
        listmuni.Add("Arivechi");
        listmuni.Add("Arizpe");
        listmuni.Add("Atil");
        listmuni.Add("Bacadéhuachi");
        listmuni.Add("Bacanora");
        listmuni.Add("Bacerac");
        listmuni.Add("Bacoachi");
        listmuni.Add("Bácum");
        listmuni.Add("Banámichi");
        listmuni.Add("Baviácora");
        listmuni.Add("Bavispe");
        listmuni.Add("Benito Juárez");
        listmuni.Add("Es Caborca!!!");
        listmuni.Add("Caborca");
        listmuni.Add("Cajeme");
        listmuni.Add("Cananea");
        listmuni.Add("Carbó");
        listmuni.Add("Cucurpe");
        listmuni.Add("Cumpas");
        listmuni.Add("Divisaderos");
        listmuni.Add("Empalme");
        listmuni.Add("Etchojoa");
        listmuni.Add("Fronteras");
        listmuni.Add("Granados");
        listmuni.Add("Guaymas");
        listmuni.Add("Hermosillo");
        listmuni.Add("Huachinera");
        listmuni.Add("Huásabas");
        listmuni.Add("Huatabampo");
        listmuni.Add("Huépac");
        listmuni.Add("Imuris");
        listmuni.Add("La Colorada");
        listmuni.Add("Magdalena de Kino");
        listmuni.Add("Mazatan");
        listmuni.Add("Moctezuma");
        listmuni.Add("Naco");
        listmuni.Add("Nácori Chico");
        listmuni.Add("Nacozari de García");
        listmuni.Add("Navojoa");
        listmuni.Add("Nogales");
        listmuni.Add("Onavas");
        listmuni.Add("Opodepe");
        listmuni.Add("Oquitoa");
        listmuni.Add("Pitiquito");
        listmuni.Add("Puerto Peñasco");
        listmuni.Add("Plutarco Elías Calles");
        listmuni.Add("Quiriego");
        listmuni.Add("Rayón");
        listmuni.Add("Rosario de Tesopaco");
        listmuni.Add("Sahuaripa");
        listmuni.Add("San Felipe de Jesús");
        listmuni.Add("San Ignacio Río Muerto");
        listmuni.Add("San Javier");
        listmuni.Add("San Luis Río Colorado");
        listmuni.Add("San Miguel de Horcasitas");
        listmuni.Add("San Pedro de la Cueva");
        listmuni.Add("Santa Ana");
        listmuni.Add("Santa Cruz");
        listmuni.Add("Sáric");
        listmuni.Add("Soyopa");
        listmuni.Add("Suaqui Grande");
        listmuni.Add("Tepache");
        listmuni.Add("Trincheras");
        listmuni.Add("Tubutama");
        listmuni.Add("Ures");
        listmuni.Add("Villa Hidalgo");
        listmuni.Add("Villa Pesqueira");
        listmuni.Add("Yécora");

            return listmuni;
        }
    }
}
